---
title: "Guinee-VHF Variable list"
author: "CDC/OMS"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: yes
  word_document:
  - toc: yes
  
header-includes:
- \usepackage[section]{placeins}
- \usepackage{setspace}
- \usepackage{relsize}
---

```{r setup, echo=FALSE, results='hide', message=FALSE, warning=FALSE }
options(tz="GMT+0")
Sys.setenv(TZ='GMT+0')

library(knitr)
opts_chunk$set( echo=FALSE, message=FALSE, comment="", 
                warnings=FALSE, results='asis')

library(Hmisc)
library(lubridate)
library(XLConnect, quietly=TRUE)
library(dplyr, quietly=TRUE) # order is important...

```


# Contacts

```{r read_contacts}

# In order for this import to work, must do 2 things first:
# 1. Make sure Region settings (control panel) are set to English(UK)
# 2. open csv file in excel, then save as an excel spreadsheet.

dir = 'C:\\Users\\bzp3\\Desktop\\_Ebola\\VHF\\fieldData\\'

file.name = "guinea_contacts_10_Oct"
excel.file = paste0(dir, file.name, '.xlsx') 
wb = loadWorkbook(excel.file)
database10 = readWorksheet(wb, file.name)

file.name = "guinea_contacts_23_Oct"
excel.file = paste0(dir, file.name, '.xlsx') 
wb = loadWorkbook(excel.file)
database23 = readWorksheet(wb, file.name)

file.name = "Contacts-OMS-online"
excel.file = paste0(dir, file.name, '.xlsx') 
wb = loadWorkbook(excel.file)
online = readWorksheet(wb, 'Online DB.csv')

file.name = "Contacts-OMS-offline"
excel.file = paste0(dir, file.name, '.xlsx') 
wb = loadWorkbook(excel.file)
offline = readWorksheet(wb, 'Offline DB Sarata 7_Oct_CLEANED')

file.name = "Contacts-all-merged"
excel.file = paste0(dir, file.name, '.xls') 
wb = loadWorkbook(excel.file)
all_merged = readWorksheet(wb, 'contacts')

load('cases.rda')
```


```{r describe_contacts}

cols = c('ThisContactIsAlsoCase', 'District', 'SubCounty', 'Village', 'DateLastContact') 
d = database10[, cols] %>%
  mutate( week = week(ymd(DateLastContact))
          ) %>%
  describe()
latex(d, append=TRUE, file='')

d = database23[, cols] %>%
  mutate( week = week(ymd(DateLastContact))
          ) %>%
  describe()
latex(d, append=TRUE, file='')

d = online[, cols] %>%
  mutate( week = week(ymd(DateLastContact))
          ) %>%
  describe()
latex(d, append=TRUE, file='')

d = offline[, cols] %>%
  mutate( week = week(ymd(DateLastContact))
          ) %>%
  describe()
latex(d, append=TRUE, file='')

d = all_merged[, cols] %>%
  mutate( week = week(ymd(DateLastContact))
          ) %>%
  describe()
latex(d, append=TRUE, file='')
```

# All_merged versus online 
```{r}
missing = all_merged %>% anti_join(database23, by='GlobalRecordId')
cat('* There are', nrow(missing), 'records missing from database that are in the offline file.\n')

missing = database23 %>% anti_join(all_merged, by='GlobalRecordId')
cat('* There are', nrow(missing), 'records in online database that are ++not++ in the offline file.')


```

